Make this script executable by doas users
- Since doas isn't permitted for root, one can't run this script with doas
- This is the most elegant solution to this, but people will not be able to run this as root

diff --git a/usr/local/bin/upgrade-packages b/usr/local/bin/upgrade-packages
--- a/usr/local/bin/upgrade-packages
+++ b/usr/local/bin/upgrade-packages
@@ -9,5 +9,11 @@
 # -----
 ###
 
-doas -u 1000 paru
-flatpak --system update
+# If current user is root, don't do anything
+if [[ "$UID" -eq 0 ]]; then
+    echo "ERROR: You can't run this script as root!"
+    exit 1
+fi
+
+paru
+doas flatpak --system update
